### ISSUE TITLE
Issue on first big upload

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/data-multi-subject_DO-NOT-USE#1]
~~~
julien-macbook:~/data/spineGeneric_multi $ gp
Enumerating objects: 4449, done.
Counting objects: 100% (4449/4449), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4448/4448), done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly | 136.00 KiB/s   
Writing objects: 100% (4449/4449), 10.13 GiB | 5.82 MiB/s, done.
Total 4449 (delta 1524), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date
~~~

**Comment by jcohenadad** [comment]
The annoying thing is that re-doing a `git push` starts the upload from scratch again (instead of continuing where it failed).

**Comment by kousu** [comment]
Is the upload just too large? Maybe you're hitting an undocumented limit in github's setup?

**Comment by jcohenadad** [comment]
> undocumented limit

you mean, there could be another limit than the max 100MB per file and max 100GB per repos?

i'm currently trying again. If it fails again, i'll switch to ssh (currently using https).

**Comment by jcohenadad** [comment]
tried again, now receiving another error: ``error: RPC failed; curl 55 SSL_write() returned SYSCALL, errno = 32`` pointing to [this possible solution](https://github.community/t/error-rpc-failed-curl-55-openssl-ssl-write-ssl-error-zero-return-errno-10053/2226/7)

**Comment by jcohenadad** [comment]
> Is the upload just too large? Maybe you're hitting an undocumented limit in github's setup?

yup! https://github.com/spine-generic/data-multi-subject/issues/2#issue-648453102

**Comment by kousu** [comment]
The error is an unceremonious disconnection. It's the sort of thing that would happen if the server hits a RAM or a file-descriptors limit, or segfaults.

**Comment by jcohenadad** [comment]
won't fix, but we don't have to do big uploads anymore 😅
