### ISSUE TITLE
Flag brnoUhb is not defined in dict flags

### ISSUE THREAD

**Issue by PaulBautin** [spine-generic/data-multi-subject_DO-NOT-USE#10]
When running sg_generate_figure `ERROR: Flag brnoUhb is not defined in dict flags` is printed. It seems the function `add_flag` does not work for this subject. Any idea?

**Full output:**
paul@paul:~/github/spine-generic$ sg_generate_figure -path-results sct_run_batch_20200722022726/results

Processing: DWI_RD.csv
Loop across subjects: 100%|████████████████| 250/250 [00:00<00:00, 972.42iter/s]
Subjects removed: []
ERROR: Flag brnoUhb is not defined in dict flags

**Comment by jcohenadad** [comment]
could be fixed by adding an entry in the dict that defines the flags per site. see in the function

**Comment by PaulBautin** [comment]
Is mountSinai ==> mountSinai hospital (Canada)?

**Comment by jcohenadad** [comment]
> Is mountSinai ==> mountSinai hospital (Canada)?

US: https://www.mountsinai.org/

**Comment by valosekj** [comment]
`brno` was renamed to `brnoUhb` in this [PR](https://github.com/spine-generic/spine-generic/pull/55). But we forgot to fix the [flags](https://github.com/spine-generic/spine-generic/blob/668dc2e2e7b02ca94b18fde0557234315fcfd73d/spinegeneric/cli/generate_figure.py#L72) dict.

EDIT:
(And, `brnoPrisma` was renamed to `brnoCeitec`.)

**Comment by jcohenadad** [comment]
> `brno` was renamed to `brnoUhb` in this [PR](https://github.com/spine-generic/spine-generic/pull/55). But we forgot to fix the [flags](https://github.com/spine-generic/spine-generic/blob/668dc2e2e7b02ca94b18fde0557234315fcfd73d/spinegeneric/cli/generate_figure.py#L72) dict.

@PaulBautin can you fix it? it's trivial

**Comment by PaulBautin** [comment]
> @PaulBautin can you fix it? it's trivial

Doing it right now,
