### ISSUE TITLE
Add json file in derivatives/labels?

### ISSUE THREAD

**Issue by charleygros** [spine-generic/data-multi-subject_DO-NOT-USE#7]
Do we need / want to add a json file for each label file?
Which could contain rater name and date for example?

**Comment by jcohenadad** [comment]
Ah geeze I forgot about this :-(. Such a pain to create those. I’m tempted to say that GH does inform about this, but once the data is downloaded the info is not visible. So yes, maybe we should enforce that.

**Comment by jcohenadad** [comment]
will be addressed in https://github.com/spine-generic/spine-generic/issues/143

**Comment by jcohenadad** [comment]
Fixed in #143
